### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by Max-Doom** [Sheepy1337/Youtube-LiveStream-ViewBot#1]
hey,
i am fixing patched youtube 2020 vbot but i am new in vbot kind of things can you help me to fix this ii changed request link and user agents but still not working  maybe i am doing in wrong way codes is in c# 

Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1

string request = string.Format("https://s.youtube.com/api/stats/watchtime?ns=yt&el=detailpage&cpn={0}&docid={1}&ver=2&referrer=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D{2}&cmt={3}&plid={4}&ei={5}&fmt=136&fs=0&rt={6}&of={7}&euri&lact={8}&live=dvr&cl={9}&state=playing&vm={10}&volume={11}&c=WEB&cver={12}&cplayer=UNIPLAYER&cbrand=apple&cbr=Safari%20Mobile&cbrver=12.1.15E148&cmodel=iphone&cos=iPhone&cosver=12_2&cplatform=MOBILE&delay=5&hl={17}&cr={18}&rtn={19}&afmt=140&lio=1556394045.182&idpj={21}&ldpj={22}&rti={23}&muted=0&st={24}&et={25}", (object)cpn, (object)Program.docid, (object)Program.docid, (object)str2, (object)plid, (object)ei, (object)str3, (object)of, (object)lact, (object)cl, (object)vm, (object)vol, (object)cver, (object)cbr, (object)cbrver, (object)cos, (object)cosver, (object)hl, (object)cr, (object)num3, (object)rndval, (object)idpj, (object)ldpj, (object)num4, (object)str1, (object)str2);

**Comment by Sheepy1337** [comment]
Can u explain a bit more what is not working?

**Comment by Max-Doom** [comment]
self1.Substring("plid=", "\\", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("ei=", "&", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("oid\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("ptchn\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("visitorData\":\"", "\"", 0, StringComparison.Ordinal, (string) null).Replace("%3D", "=");
          self1.Substring("cver\",\"value\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("blazer\",\"cver\":\":", "\"", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("PAGE_BUILD_LABEL\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("VARIANTS_CHECKSUM\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("c\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("INNERTUBE_CONTEXT_HL\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("\"hl\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("cr\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("INNERTUBE_CONTEXT_GL\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("INNERTUBE_API_KEY\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("of=", "\\", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("vm=", "\\", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("idpj\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("ldpj\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          self1.Substring("ps\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          (num44 + 300.0).ToString().Replace(",", ".");
          num55.ToString().Replace(",", ".");
          random11.Next(0, 10);
          num44.ToString().Replace(",", ".");
         
          string str11 = self1.Substring("ei=", "\\", 0, StringComparison.Ordinal, (string) null);
          string str12 = self1.Substring("INNERTUBE_CONTEXT_CLIENT_VERSION\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          string str13 = self1.Substring("PAGE_CL\":", ",", 0, StringComparison.Ordinal, (string) null);
          string str14 = self1.Substring("c\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          string str15 = self1.Substring("hl\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          string str16 = self1.Substring("cr\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          string str17 = self1.Substring("of=", "\\", 0, StringComparison.Ordinal, (string) null);
          string str18 = self1.Substring("vm=", "\\", 0, StringComparison.Ordinal, (string) null);
          string str19 = self1.Substring("idpj\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          string str20 = self1.Substring("ldpj\":\"", "\"", 0, StringComparison.Ordinal, (string) null);
          httpRequest1.AddHeader(HttpHeader.Accept, "image/png,image/svg+xml,image/*;q=0.8,video/*;q=0.8,*lllllllllllllllll/*;q=0.5");
          httpRequest1.AddHeader(HttpHeader.AcceptLanguage, "ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3");
          httpRequest1.AddHeader(HttpHeader.Referer, "https://m.youtube.com/watch?v=" + Class1.string_0);
          httpRequest1.Get("https://s.youtube.com/api/stats/watchtime?ns=yt&el=detailpage&cpn=" + Class1.smethod_2(16) + "&docid=" + Class1.string_0 + "&ver=2&cmt=" + num11.ToString().Replace(",", ".") + "&ei=" + str11 + "&fmt=133&fs=0&rt=" + num22.ToString().Replace(",", ".") + "&of=" + str17 + "&euri&lact=" + (object) num33 + "&live=dvr&cl=" + str13 + "&state=playing&vm=" + str18 + "&volume=100&c=" + str14 + "&cver=" + str12 + "&cplayer=UNIPLAYER&cbrand=apple&cbr=Safari%20Mobile&cbrver=12.1.15E148&cmodel=iphone&cos=iPhone&cosver=12_2&cplatform=MOBILE&delay=5&hl=" + str15 + "&cr=" + str16 + "&rtn=" + (object) (num22 + 300) + "&afmt=140&lio=1556394045.182&idpj=" + str19 + "&ldpj=" + str20 + "&rti=" + (object) num22 + "&muted=0&st=" + num11.ToString().Replace(",", ".") + "&et=" + ((double) num11 + 300.0).ToString().Replace(",", "."), (RequestParams) null).ToString();
         
          Colorful.Console.WriteLine(string_0+"\n" + httpRequest1.UserAgent +"  Ip  "+ httpRequest1.Proxy);
          Class1.smethod_7(Class1.smethod_6() + 1);
          Thread.Sleep(20000);

**Comment by Max-Doom** [comment]
see these are the issues when I put exception in codes and compile it, i am not getting problem in compiling 
![Caccvture](https://user-images.githubusercontent.com/63877534/79670422-b9695200-8177-11ea-9419-2287a6a84c05.PNG)

**Comment by Sheepy1337** [comment]
well thats just the dead proxies not being able to connect to youtube's server, look at the exception: Unable to connect to the http server

**Comment by Max-Doom** [comment]
bro, then it is not working can you connect me on discord, this is special bot it goes in 50k+, I am not talking too much here, please inform me if you are able to work with me and fix it

**Comment by Max-Doom** [comment]
this is my discord id  I͜͡'AM乛D.O.O.M#2744

**Comment by Sheepy1337** [comment]
added you

**Comment by Max-Doom** [comment]
hey whats you id name

**Comment by Max-Doom** [comment]
on discord

**Comment by Sheepy1337** [comment]
NotSheepy#4728
