### ISSUE TITLE
its not working anymore

### ISSUE THREAD

**Issue by tanboy4u** [Sheepy1337/Youtube-LiveStream-ViewBot#2]
its not working anymore

**Comment by Sheepy1337** [comment]
What is not working, please be more detailed on what you did and if possible what the error is

**Comment by tanboy4u** [comment]
the bott numbers stays zero

**Comment by tanboy4u** [comment]
it doesn't count bots and the views doesn't raise up .

**Comment by tanboy4u** [comment]
add me to discord i will show you my screen A7madco#5068

**Comment by Sheepy1337** [comment]
Answered on discord, closing
