### ISSUE TITLE
Jumps viewer 

### ISSUE THREAD

**Issue by HeartWell** [Sheepy1337/Youtube-LiveStream-ViewBot#4]
Thank you for the software, you are the best. How to remove jumps viewer?  Because jumps 100 to 500 every time.

**Comment by HeartWell** [comment]
No info?

**Comment by Sheepy1337** [comment]
Yea its a issue with the threading, i got a updated version if u are interested add me on discord NotSheepy#4728

**Comment by HeartWell** [comment]
I add.
